### ISSUE TITLE
./autogen.sh error with perl

### ISSUE THREAD

**Issue by MoffD** [Malvineous/xargon#1]
Hey Mal! I got an error after downloading the git version and running ./autogen.sh:
/usr/bin/perl: symbol lookup error: /usr/lib/perl5/vendor_perl/auto/IO/IO.so: undefined symbol: Perl_xs_apiversion_bootcheck
trying to compile on 64 bit Arch Linux, if it helps:
Perl version: (v5.22.0)
uname -rvm: 4.0.7-2-ARCH #1 SMP PREEMPT Tue Jun 30 07:50:21 UTC 2015 x86_64
Thanks in advance!

**Comment by MoffD** [comment]
Nevermind... a perl update fixed the issue, sorry for bothering you

**Comment by Malvineous** [comment]
No worries, glad you got it sorted!
